### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NeguinhoAdmin** [Laravel-Backpack/community-forum#1114]
# Bug report

### What I did

It was working surprisingly for more than 2 weeks and now it gives following problem. And today same thing giving me that problem

### What I expected to happen

This is customised report suppose to show.

```
        $this->crud->query->leftJoin('application_items', 'motorbike_annual_compliance.motorbike_id', '=', 'application_items.motorbike_id')
            ->leftJoin('finance_applications', 'application_items.application_id', '=', 'finance_applications.id')
            ->leftJoin('customers as app_customers', 'finance_applications.customer_id', '=', 'app_customers.id')
            ->leftJoin('renting_booking_items', 'motorbike_annual_compliance.motorbike_id', '=', 'renting_booking_items.motorbike_id')
            ->leftJoin('renting_bookings', 'renting_booking_items.booking_id', '=', 'renting_bookings.id')
            ->leftJoin('customers as rent_customers', 'renting_bookings.customer_id', '=', 'rent_customers.id')
            ->leftJoin('motorbikes_sale', 'motorbike_annual_compliance.motorbike_id', '=', 'motorbikes_sale.motorbike_id')
            ->leftJoin('company_vehicles', 'motorbike_annual_compliance.motorbike_id', '=', 'company_vehicles.motorbike_id')
            ->leftJoin('motorbikes', 'motorbike_annual_compliance.motorbike_id', '=', 'motorbikes.id')
            ->leftJoin('recovered_motorbikes', 'motorbike_annual_compliance.motorbike_id', '=', 'recovered_motorbikes.motorbike_id')
            ->leftJoin('claim_motorbikes', 'motorbike_annual_compliance.motorbike_id', '=', 'claim_motorbikes.motorbike_id')
            ->whereNull('renting_booking_items.end_date')

            ->select('motorbike_annual_compliance.*', 'motorbikes_sale.is_sold', \DB::raw("
            CASE
                WHEN company_vehicles.motorbike_id IS NOT NULL THEN 'COMPANY VEHICLE'
                WHEN application_items.motorbike_id IS NOT NULL AND finance_applications.log_book_sent = true THEN CONCAT('INSTALLMENT SOLD: ', app_customers.first_name, ' ', app_customers.last_name)
                WHEN application_items.motorbike_id IS NOT NULL AND
                        recovered_motorbikes.motorbike_id IS NULL
                    THEN
                        CONCAT('INSTALLMENT: ', app_customers.first_name, ' ', app_customers.last_name)
                WHEN application_items.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.case_date > application_items.updated_at THEN
                'RECOVERED'
                WHEN renting_booking_items.motorbike_id IS NOT NULL AND renting_booking_items.end_date IS NULL THEN CONCAT('RENTAL: ', rent_customers.first_name, ' ', rent_customers.last_name)
                WHEN claim_motorbikes.motorbike_id IS NOT NULL THEN 'CLAIM'
                WHEN application_items.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.motorbike_id IS NOT NULL AND
                    renting_booking_items.motorbike_id IS NOT NULL AND
                    renting_booking_items.start_date < recovered_motorbikes.case_date AND
                    renting_booking_items.end_date IS NOT NULL
                    THEN 'AVAILABLE'
                WHEN motorbikes_sale.motorbike_id IS NOT NULL AND motorbikes_sale.is_sold = true THEN 'SOLD'
                WHEN motorbikes_sale.motorbike_id IS NOT NULL THEN 'SALE'

                ELSE 'MOT/SUBSCRIBER'
            END as association_status
        "))->orderBy('motorbike_annual_compliance.id', 'desc');
```

I have added this line ->orderBy('motorbike_annual_compliance.id', 'desc') later.

### What happened

<img width="550" alt="image" src="https://github.com/user-attachments/assets/bee017c2-40a4-44c5-b168-4baaf3fed066">

### What I've already tried to fix it

try to override existing by adding line ->orderBy('motorbike_annual_compliance.id', 'desc') . But still probelm
and If I remove "order by" it still coming from Backpack 
<img width="628" alt="image" src="https://github.com/user-attachments/assets/b3b9d9a4-b584-442a-9630-752f424d5193">

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

php artisan backpack:version
### PHP VERSION:
8.2.20

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, i360, iconv, igbinary, imagick, imap, intl, exif, mongodb, msgpack, mysqli, odbc, pdo_dblib, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, memcached, Zend OPcache

### LARAVEL VERSION:
10.48.20.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.5
backpack/calendar-operation: 1.0.5
backpack/crud: 6.7.26
backpack/generators: v4.0.5
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.13
backpack/theme-coreuiv4: 1.1.2

**Comment by NeguinhoAdmin** [comment]
Complete Log
```

[2024-08-12 11:43:37] production.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '."id" desc limit 10' at line 26 (Connection: mysql, SQL: select `motorbike_annual_compliance`.*, `motorbikes_sale`.`is_sold`, 
            CASE
                WHEN company_vehicles.motorbike_id IS NOT NULL THEN 'COMPANY VEHICLE'
                WHEN application_items.motorbike_id IS NOT NULL AND finance_applications.log_book_sent = true THEN CONCAT('INSTALLMENT SOLD: ', app_customers.first_name, ' ', app_customers.last_name)
                WHEN application_items.motorbike_id IS NOT NULL AND
                        recovered_motorbikes.motorbike_id IS NULL
                    THEN
                        CONCAT('INSTALLMENT: ', app_customers.first_name, ' ', app_customers.last_name)
                WHEN application_items.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.case_date > application_items.updated_at THEN
                'RECOVERED'
                WHEN renting_booking_items.motorbike_id IS NOT NULL AND renting_booking_items.end_date IS NULL THEN CONCAT('RENTAL: ', rent_customers.first_name, ' ', rent_customers.last_name)
                WHEN claim_motorbikes.motorbike_id IS NOT NULL THEN 'CLAIM'
                WHEN application_items.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.motorbike_id IS NOT NULL AND
                    renting_booking_items.motorbike_id IS NOT NULL AND
                    renting_booking_items.start_date < recovered_motorbikes.case_date AND
                    renting_booking_items.end_date IS NOT NULL
                    THEN 'AVAILABLE'
                WHEN motorbikes_sale.motorbike_id IS NOT NULL AND motorbikes_sale.is_sold = true THEN 'SOLD'
                WHEN motorbikes_sale.motorbike_id IS NOT NULL THEN 'SALE'

                ELSE 'MOT/SUBSCRIBER'
            END as association_status
         from `motorbike_annual_compliance` left join `application_items` on `motorbike_annual_compliance`.`motorbike_id` = `application_items`.`motorbike_id` left join `finance_applications` on `application_items`.`application_id` = `finance_applications`.`id` left join `customers` as `app_customers` on `finance_applications`.`customer_id` = `app_customers`.`id` left join `renting_booking_items` on `motorbike_annual_compliance`.`motorbike_id` = `renting_booking_items`.`motorbike_id` left join `renting_bookings` on `renting_booking_items`.`booking_id` = `renting_bookings`.`id` left join `customers` as `rent_customers` on `renting_bookings`.`customer_id` = `rent_customers`.`id` left join `motorbikes_sale` on `motorbike_annual_compliance`.`motorbike_id` = `motorbikes_sale`.`motorbike_id` left join `company_vehicles` on `motorbike_annual_compliance`.`motorbike_id` = `company_vehicles`.`motorbike_id` left join `motorbikes` on `motorbike_annual_compliance`.`motorbike_id` = `motorbikes`.`id` left join `recovered_motorbikes` on `motorbike_annual_compliance`.`motorbike_id` = `recovered_motorbikes`.`motorbike_id` left join `claim_motorbikes` on `motorbike_annual_compliance`.`motorbike_id` = `claim_motorbikes`.`motorbike_id` where `renting_booking_items`.`end_date` is null order by "motorbike_annual_compliance"."id" desc limit 10) {"userId":93,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.\"id\" desc limit 10' at line 26 (Connection: mysql, SQL: select `motorbike_annual_compliance`.*, `motorbikes_sale`.`is_sold`, 
            CASE
                WHEN company_vehicles.motorbike_id IS NOT NULL THEN 'COMPANY VEHICLE'
                WHEN application_items.motorbike_id IS NOT NULL AND finance_applications.log_book_sent = true THEN CONCAT('INSTALLMENT SOLD: ', app_customers.first_name, ' ', app_customers.last_name)
                WHEN application_items.motorbike_id IS NOT NULL AND
                        recovered_motorbikes.motorbike_id IS NULL
                    THEN
                        CONCAT('INSTALLMENT: ', app_customers.first_name, ' ', app_customers.last_name)
                WHEN application_items.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.case_date > application_items.updated_at THEN
                'RECOVERED'
                WHEN renting_booking_items.motorbike_id IS NOT NULL AND renting_booking_items.end_date IS NULL THEN CONCAT('RENTAL: ', rent_customers.first_name, ' ', rent_customers.last_name)
                WHEN claim_motorbikes.motorbike_id IS NOT NULL THEN 'CLAIM'
                WHEN application_items.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.motorbike_id IS NOT NULL AND
                    renting_booking_items.motorbike_id IS NOT NULL AND
                    renting_booking_items.start_date < recovered_motorbikes.case_date AND
                    renting_booking_items.end_date IS NOT NULL
                    THEN 'AVAILABLE'
                WHEN motorbikes_sale.motorbike_id IS NOT NULL AND motorbikes_sale.is_sold = true THEN 'SOLD'
                WHEN motorbikes_sale.motorbike_id IS NOT NULL THEN 'SALE'

                ELSE 'MOT/SUBSCRIBER'
            END as association_status
         from `motorbike_annual_compliance` left join `application_items` on `motorbike_annual_compliance`.`motorbike_id` = `application_items`.`motorbike_id` left join `finance_applications` on `application_items`.`application_id` = `finance_applications`.`id` left join `customers` as `app_customers` on `finance_applications`.`customer_id` = `app_customers`.`id` left join `renting_booking_items` on `motorbike_annual_compliance`.`motorbike_id` = `renting_booking_items`.`motorbike_id` left join `renting_bookings` on `renting_booking_items`.`booking_id` = `renting_bookings`.`id` left join `customers` as `rent_customers` on `renting_bookings`.`customer_id` = `rent_customers`.`id` left join `motorbikes_sale` on `motorbike_annual_compliance`.`motorbike_id` = `motorbikes_sale`.`motorbike_id` left join `company_vehicles` on `motorbike_annual_compliance`.`motorbike_id` = `company_vehicles`.`motorbike_id` left join `motorbikes` on `motorbike_annual_compliance`.`motorbike_id` = `motorbikes`.`id` left join `recovered_motorbikes` on `motorbike_annual_compliance`.`motorbike_id` = `recovered_motorbikes`.`motorbike_id` left join `claim_motorbikes` on `motorbike_annual_compliance`.`motorbike_id` = `claim_motorbikes`.`motorbike_id` where `renting_booking_items`.`end_date` is null order by \"motorbike_annual_compliance\".\"id\" desc limit 10) at /Users/adminneguinho/Sites/NGM-WEB/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
[stacktrace]
#0 /Users/adminneguinho/Sites/NGM-WEB/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\\Database\\Connection->runQueryCallback('select `motorbi...', Array, Object(Closure))...

[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.\"id\" desc limit 10' at line 26 at /Users/adminneguinho/Sites/NGM-WEB/vendor/laravel/framework/src/Illuminate/Database/Connection.php:423)
[stacktrace]
#0 /Users/adminneguinho/Sites/NGM-WEB/vendor/laravel/framework/src/Illuminate/Database/Connection.php(423): PDO->prepare('select `motorbi...')
[2024-08-12 11:43:37] production.INFO: array (
)  
[2024-08-12 11:43:37] production.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '."id" desc limit 10' at line 26 (Connection: mysql, SQL: select `motorbike_annual_compliance`.*, `motorbikes_sale`.`is_sold`, 
            CASE
                WHEN company_vehicles.motorbike_id IS NOT NULL THEN 'COMPANY VEHICLE'
                WHEN application_items.motorbike_id IS NOT NULL AND finance_applications.log_book_sent = true THEN CONCAT('INSTALLMENT SOLD: ', app_customers.first_name, ' ', app_customers.last_name)
                WHEN application_items.motorbike_id IS NOT NULL AND
                        recovered_motorbikes.motorbike_id IS NULL
                    THEN
                        CONCAT('INSTALLMENT: ', app_customers.first_name, ' ', app_customers.last_name)
                WHEN application_items.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.case_date > application_items.updated_at THEN
                'RECOVERED'
                WHEN renting_booking_items.motorbike_id IS NOT NULL AND renting_booking_items.end_date IS NULL THEN CONCAT('RENTAL: ', rent_customers.first_name, ' ', rent_customers.last_name)
                WHEN claim_motorbikes.motorbike_id IS NOT NULL THEN 'CLAIM'
                WHEN application_items.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.motorbike_id IS NOT NULL AND
                    renting_booking_items.motorbike_id IS NOT NULL AND
                    renting_booking_items.start_date < recovered_motorbikes.case_date AND
                    renting_booking_items.end_date IS NOT NULL
                    THEN 'AVAILABLE'
                WHEN motorbikes_sale.motorbike_id IS NOT NULL AND motorbikes_sale.is_sold = true THEN 'SOLD'
                WHEN motorbikes_sale.motorbike_id IS NOT NULL THEN 'SALE'

                ELSE 'MOT/SUBSCRIBER'
            END as association_status
         from `motorbike_annual_compliance` left join `application_items` on `motorbike_annual_compliance`.`motorbike_id` = `application_items`.`motorbike_id` left join `finance_applications` on `application_items`.`application_id` = `finance_applications`.`id` left join `customers` as `app_customers` on `finance_applications`.`customer_id` = `app_customers`.`id` left join `renting_booking_items` on `motorbike_annual_compliance`.`motorbike_id` = `renting_booking_items`.`motorbike_id` left join `renting_bookings` on `renting_booking_items`.`booking_id` = `renting_bookings`.`id` left join `customers` as `rent_customers` on `renting_bookings`.`customer_id` = `rent_customers`.`id` left join `motorbikes_sale` on `motorbike_annual_compliance`.`motorbike_id` = `motorbikes_sale`.`motorbike_id` left join `company_vehicles` on `motorbike_annual_compliance`.`motorbike_id` = `company_vehicles`.`motorbike_id` left join `motorbikes` on `motorbike_annual_compliance`.`motorbike_id` = `motorbikes`.`id` left join `recovered_motorbikes` on `motorbike_annual_compliance`.`motorbike_id` = `recovered_motorbikes`.`motorbike_id` left join `claim_motorbikes` on `motorbike_annual_compliance`.`motorbike_id` = `claim_motorbikes`.`motorbike_id` where `renting_booking_items`.`end_date` is null order by "motorbike_annual_compliance"."id" desc limit 10) {"userId":93,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.\"id\" desc limit 10' at line 26 (Connection: mysql, SQL: select `motorbike_annual_compliance`.*, `motorbikes_sale`.`is_sold`, 
            CASE
                WHEN company_vehicles.motorbike_id IS NOT NULL THEN 'COMPANY VEHICLE'
                WHEN application_items.motorbike_id IS NOT NULL AND finance_applications.log_book_sent = true THEN CONCAT('INSTALLMENT SOLD: ', app_customers.first_name, ' ', app_customers.last_name)
                WHEN application_items.motorbike_id IS NOT NULL AND
                        recovered_motorbikes.motorbike_id IS NULL
                    THEN
                        CONCAT('INSTALLMENT: ', app_customers.first_name, ' ', app_customers.last_name)
                WHEN application_items.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.case_date > application_items.updated_at THEN
                'RECOVERED'
                WHEN renting_booking_items.motorbike_id IS NOT NULL AND renting_booking_items.end_date IS NULL THEN CONCAT('RENTAL: ', rent_customers.first_name, ' ', rent_customers.last_name)
                WHEN claim_motorbikes.motorbike_id IS NOT NULL THEN 'CLAIM'
                WHEN application_items.motorbike_id IS NOT NULL AND
                    recovered_motorbikes.motorbike_id IS NOT NULL AND
                    renting_booking_items.motorbike_id IS NOT NULL AND
                    renting_booking_items.start_date < recovered_motorbikes.case_date AND
                    renting_booking_items.end_date IS NOT NULL
                    THEN 'AVAILABLE'
                WHEN motorbikes_sale.motorbike_id IS NOT NULL AND motorbikes_sale.is_sold = true THEN 'SOLD'
                WHEN motorbikes_sale.motorbike_id IS NOT NULL THEN 'SALE'

                ELSE 'MOT/SUBSCRIBER'
            END as association_status
         from `motorbike_annual_compliance` left join `application_items` on `motorbike_annual_compliance`.`motorbike_id` = `application_items`.`motorbike_id` left join `finance_applications` on `application_items`.`application_id` = `finance_applications`.`id` left join `customers` as `app_customers` on `finance_applications`.`customer_id` = `app_customers`.`id` left join `renting_booking_items` on `motorbike_annual_compliance`.`motorbike_id` = `renting_booking_items`.`motorbike_id` left join `renting_bookings` on `renting_booking_items`.`booking_id` = `renting_bookings`.`id` left join `customers` as `rent_customers` on `renting_bookings`.`customer_id` = `rent_customers`.`id` left join `motorbikes_sale` on `motorbike_annual_compliance`.`motorbike_id` = `motorbikes_sale`.`motorbike_id` left join `company_vehicles` on `motorbike_annual_compliance`.`motorbike_id` = `company_vehicles`.`motorbike_id` left join `motorbikes` on `motorbike_annual_compliance`.`motorbike_id` = `motorbikes`.`id` left join `recovered_motorbikes` on `motorbike_annual_compliance`.`motorbike_id` = `recovered_motorbikes`.`motorbike_id` left join `claim_motorbikes` on `motorbike_annual_compliance`.`motorbike_id` = `claim_motorbikes`.`motorbike_id` where `renting_booking_items`.`end_date` is null order by \"motorbike_annual_compliance\".\"id\" desc limit 10) at /Users/adminneguinho/Sites/NGM-WEB/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
[stacktrace]

[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.\"id\" desc limit 10' at line 26 at /Users/adminneguinho/Sites/NGM-WEB/vendor/laravel/framework/src/Illuminate/Database/Connection.php:423)
[stacktrace]
#0 /Users/adminneguinho/Sites/NGM-WEB/vendor/laravel/framework/src/Illuminate/Database/Connection.php(423): PDO->prepare('select `motorbi...'). 

```

**Comment by NeguinhoAdmin** [comment]
this line solved my problem.

Is it override?
$this->crud->query->orderByRaw('motorbike_annual_compliance.id');
