### ISSUE TITLE
How to deploy Laravel+Backpack to Laravel Vapor

### ISSUE THREAD

**Issue by mwisner** [Laravel-Backpack/community-forum#155]
# Bug report

I'm not really sure if this is a Larval Vapor, or Laraval Backpack issue... but I figured I would start here. 

# Problem 1 Build size
For Laravel Vapor, your application must be less than 45MB compressed. the packages provided by backpack take up a considerable amount of that. 

Workaround solution:
Delete the packages from the vendor file before uploading.
```
    build:
      - 'rm -rf vendor/backpack/crud/src/public/packages'
```

Docs: https://docs.vapor.build/1.0/projects/deployments.html#build-hooks

# Problem 2: Exception during initialization 
Looks like $_SERVER['REMOTE_ADDR'] isn't set at this point.

```
Caching Laravel configuration[2019-10-02 13:57:34] staging.ERROR: Undefined index: REMOTE_ADDR {"exception":"[object] (ErrorException(code: 0): Undefined index: REMOTE_ADDR at /var/task/vendor/backpack/crud/src/LicenseCheck.php:22)

17:57:34
[stacktrace]

17:57:34
#0 /var/task/vendor/backpack/crud/src/LicenseCheck.php(22): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/var/task/vendo...', 22, Array)

17:57:34
Laravel-Backpack/CRUD#1 /var/task/vendor/backpack/crud/src/BackpackServiceProvider.php(45): Backpack\\CRUD\\BackpackServiceProvider->checkLicenseCodeExists()

17:57:34
Laravel-Backpack/CRUD#2 [internal function]: Backpack\\CRUD\\BackpackServiceProvider->boot(Object(Illuminate\\Routing\\Router))

17:57:34
Laravel-Backpack/CRUD#3 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)

17:57:34
Laravel-Backpack/CRUD#4 /var/task/vendor/laravel/framework/src/Illuminate/Support/helpers.php(522): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()

17:57:34
Laravel-Backpack/CRUD#5 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): value(Object(Closure))

17:57:34
Laravel-Backpack/CRUD#6 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))

17:57:34
Laravel-Backpack/CRUD#7 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(591): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)

17:57:34
Laravel-Backpack/CRUD#8 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(828): Illuminate\\Container\\Container->call(Array)

17:57:34
Laravel-Backpack/CRUD#9 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(811): Illuminate\\Foundation\\Application->bootProvider(Object(Backpack\\CRUD\\BackpackServiceProvider))

17:57:34
Laravel-Backpack/CRUD#10 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Backpack\\CRUD\\BackpackServiceProvider), 15)

17:57:34
Laravel-Backpack/CRUD#11 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(812): array_walk(Array, Object(Closure))

17:57:34
Laravel-Backpack/CRUD#12 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()

17:57:34
Laravel-Backpack/CRUD#13 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(211): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))

17:57:34
Laravel-Backpack/CRUD#14 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(320): Illuminate\\Foundation\\Application->bootstrapWith(Array)

17:57:34
Laravel-Backpack/CRUD#15 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(271): Illuminate\\Foundation\\Console\\Kernel->bootstrap()

17:57:34
Laravel-Backpack/CRUD#16 /var/task/fpmRuntime.php(65): Illuminate\\Foundation\\Console\\Kernel->call('config:cache')

17:57:34
Laravel-Backpack/CRUD#17 /var/task/vendor/laravel/framework/src/Illuminate/Support/helpers.php(548): {closure}(Object(Illuminate\\Foundation\\Application))

17:57:34
Laravel-Backpack/CRUD#18 /var/task/fpmRuntime.php(66): with(Object(Illuminate\\Foundation\\Application), Object(Closure))

17:57:34
Laravel-Backpack/CRUD#19 /var/task/runtime.php(28): require('/var/task/fpmRu...')

17:57:34
Laravel-Backpack/CRUD#20 /opt/bootstrap.php(6): require('/var/task/runti...')

17:57:34
Laravel-Backpack/CRUD#21 {main}
```
# Problem 3: Too many public assets

Due to the number of public package files published in the Laravel Backpack admin theme, (4191) (`find packages -print | wc -l`), Laravel Backpack cannot be deployed to https://vapor.laravel.com.

Laravel Vapor has a requirement of a max of `300` public assets.

```

Project built successfully. (0m24s)

==> Uploading Deployment Artifact (28.12MB)
 28792KB/28792KB [============================] 100% (< 1 sec remaining)


Whoops! There were some problems with your request.

    - Vapor applications may not have more than 300 public assets.
```

### What I did
- Attempt to deploy Backpack to our Laravel Vapor deployment.
- Attempted to delete any of the packages I thought weren't necessary for our deployment... I was only able to get down to around 600 files. 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 7.3.10 (cli) (built: Sep 30 2019 19:59:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.10, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
laravel/framework                      v6.0.4     The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                          4.0.5      Quickly build an admin in...
backpack/generators                    2.0.4      Generate files for larave...
```

```
vapor --version
Laravel Vapor 1.3.0
```

**Comment by tabacitu** [comment]
@promatik is going to test this again, on v6. With the [steps here](https://github.com/Laravel-Backpack/basset#laravel-vapor) I'm pretty sure we have a clear and valid way of deploying Backpack on Vapor.

But.

We need to make it even more clear. And have it documented in the Backpack docs. _Official_ support.
